### ISSUE TITLE
[general issue] Identical outputs regardless of different randseed

### ISSUE THREAD

**Issue by ghost** [aCOSMIC/aCOSMIC#606]
Hi, 
I'm having a problem when evolving the same initial binaries multiple times - whilst I would expect some (small) variations in the output bpp due to the various evolutionary prescriptions, I am getting the exact same bpp & bcm output with each run.  
Whilst I am generating different 'randomseed' values with each run, the outputs are identical (all masses, periods, radii etc **identical** to 6 decimal places). The kick_info for each run _is_ different, and I can't understand why the rest of the outputs are not being updated. 

I am currently running COSMIC 3.4.8, but have tried with 3.4.7 & the new 3.4.9 and have the same issue. I have tried removing and re-installing but to no avail. I would be most grateful for any advice you might have!

![image](https://github.com/COSMIC-PopSynth/COSMIC/assets/142584303/3f202783-602a-4861-9543-cf4eddd4a1c6)
![image](https://github.com/COSMIC-PopSynth/COSMIC/assets/142584303/905ebf84-a0bc-4770-a49d-0f1c07ee7848)

**Comment by katiebreivik** [comment]
Hey @cdashwoodbrown  -- I created a similar (up to 3 decimal) example to yours and I think COSMIC is doing what we'd expect. You get the exact same evolution because there aren't any stochastic processes (like kicks) that will alter the binary evolution for a system with M1=11.171, M2=6.673, Porb=170.758, e=0.0 initially. You can see the evolution below:
<img width="900" alt="Screenshot 2023-10-05 at 8 15 52 AM" src="https://github.com/COSMIC-PopSynth/COSMIC/assets/22921809/83ce981f-a15a-48f7-b8ad-dbb470ba06e7">

In this case, if you rerun with the same binary evolution model and the same initial conditions, you should get exactly the same outcomes except for the natal kick speed and direction for the initially less massive star (M2) that explodes after the 2nd common envelope phase results in a merger that leaves behind a single star that is massive enough to explode.

I hope this helps!

**Comment by ghost** [comment]
Hi Katie, thanks so much for your help - I realised as I submitted that the above was not the best example of the problem (or the best example to check from my end!). However, uninstalling and reinstalling has fixed another outlying issue and running the tests again with different parameters does seem to be working now.
I appreciate your time - and thank you so much for making this awesome code public, its the basis of a whole chapter of my PhD!

**Comment by katiebreivik** [comment]
Happy to hear that it's useful! I'm going to go ahead and close this for now.
